### ISSUE TITLE
Installation fails with `AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`.

### ISSUE THREAD

**Issue by dreirund** [INTI-CMNB/PcbDraw#14]
Using [this build recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pcbdraw-git), installation fails for me with  
`AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`:  
```
/var/cache/makepkg/build/pcbdraw-git/src/pcbdraw/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/var/cache/makepkg/build/pcbdraw-git/src/pcbdraw/setup.py", line 11, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/makepkg/build/pcbdraw-git/src/pcbdraw/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/var/cache/makepkg/build/pcbdraw-git/src/pcbdraw/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/makepkg/build/pcbdraw-git/src/pcbdraw/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

I am on python 3.12.3; python module `configparser` is at version 7.0.0.

Regards!

**Comment by dos1** [comment]
It's fixed in the upstream repo: https://github.com/yaqwsx/PcbDraw/commit/1264f28eb0cb96ab7ec44ecb09c5d50eef508ec5

**Comment by dreirund** [comment]
> It's fixed in the upstream repo: [yaqwsx@1264f28](https://github.com/yaqwsx/PcbDraw/commit/1264f28eb0cb96ab7ec44ecb09c5d50eef508ec5)

So this is fixed in [github.com/yaqwsx/PcbDraw](https://github.com/yaqwsx/PcbDraw). But not in [github.com/INTI-CMNB/PcbDraw](https://github.com/INTI-CMNB/PcbDraw/) which is the repo where this issue is here.

@maintainers, can you port this fix to here?

Regards!

**Comment by set-soft** [comment]
Hi @dreirund !

I'm not actively updating this fork because the code is now included in my main project ([KiBot](https://github.com/INTI-CMNB/KiBot)). 

In the past KiBot invoked PcbDraw as a separated tool, but now is just a python module included in KiBot.
